import unittest
import sys
sys.path.append("../lib")
from nabeatsu import Nabeatsu

class TestNabeatsu(unittest.TestCase):
    def setUp(self):
        self.nabeatsu = Nabeatsu()

    def test_go_crazy_if_ver(self):
        self.assertEqual("1", self.nabeatsu.go_crazy_if_ver(1))
        self.assertEqual("2", self.nabeatsu.go_crazy_if_ver(2))
        self.assertEqual("3!", self.nabeatsu.go_crazy_if_ver(3))
        self.assertEqual("4", self.nabeatsu.go_crazy_if_ver(4))
        self.assertEqual("5", self.nabeatsu.go_crazy_if_ver(5))
        self.assertEqual("6!", self.nabeatsu.go_crazy_if_ver(6))
        self.assertEqual("7", self.nabeatsu.go_crazy_if_ver(7))
        self.assertEqual("8", self.nabeatsu.go_crazy_if_ver(8))
        self.assertEqual("9!", self.nabeatsu.go_crazy_if_ver(9))
        self.assertEqual("10", self.nabeatsu.go_crazy_if_ver(10))
        self.assertEqual("11", self.nabeatsu.go_crazy_if_ver(11))
        self.assertEqual("12!", self.nabeatsu.go_crazy_if_ver(12))
        self.assertEqual("13!", self.nabeatsu.go_crazy_if_ver(13))
        self.assertEqual("14", self.nabeatsu.go_crazy_if_ver(14))
        self.assertEqual("15!", self.nabeatsu.go_crazy_if_ver(15))
        self.assertEqual("16", self.nabeatsu.go_crazy_if_ver(16))
        self.assertEqual("17", self.nabeatsu.go_crazy_if_ver(17))
        self.assertEqual("18!", self.nabeatsu.go_crazy_if_ver(18))
        self.assertEqual("19", self.nabeatsu.go_crazy_if_ver(19))
        self.assertEqual("20", self.nabeatsu.go_crazy_if_ver(20))
        self.assertEqual("21!", self.nabeatsu.go_crazy_if_ver(21))
        self.assertEqual("22", self.nabeatsu.go_crazy_if_ver(22))
        self.assertEqual("23!", self.nabeatsu.go_crazy_if_ver(23))
        self.assertEqual("24!", self.nabeatsu.go_crazy_if_ver(24))
        self.assertEqual("25", self.nabeatsu.go_crazy_if_ver(25))
        self.assertEqual("26", self.nabeatsu.go_crazy_if_ver(26))
        self.assertEqual("27!", self.nabeatsu.go_crazy_if_ver(27))
        self.assertEqual("28", self.nabeatsu.go_crazy_if_ver(28))
        self.assertEqual("29", self.nabeatsu.go_crazy_if_ver(29))
        self.assertEqual("30!", self.nabeatsu.go_crazy_if_ver(30))
        self.assertEqual("31!", self.nabeatsu.go_crazy_if_ver(31))
        self.assertEqual("32!", self.nabeatsu.go_crazy_if_ver(32))
        self.assertEqual("33!", self.nabeatsu.go_crazy_if_ver(33))
        self.assertEqual("34!", self.nabeatsu.go_crazy_if_ver(34))
        self.assertEqual("35!", self.nabeatsu.go_crazy_if_ver(35))
        self.assertEqual("36!", self.nabeatsu.go_crazy_if_ver(36))
        self.assertEqual("37!", self.nabeatsu.go_crazy_if_ver(37))
        self.assertEqual("38!", self.nabeatsu.go_crazy_if_ver(38))
        self.assertEqual("39!", self.nabeatsu.go_crazy_if_ver(39))
        self.assertEqual("40", self.nabeatsu.go_crazy_if_ver(40))

    def test_go_crazy_ternary_ver(self):
        self.assertEqual("1", self.nabeatsu.go_crazy_ternary_ver(1))
        self.assertEqual("2", self.nabeatsu.go_crazy_ternary_ver(2))
        self.assertEqual("3!", self.nabeatsu.go_crazy_ternary_ver(3))
        self.assertEqual("4", self.nabeatsu.go_crazy_ternary_ver(4))
        self.assertEqual("5", self.nabeatsu.go_crazy_ternary_ver(5))
        self.assertEqual("6!", self.nabeatsu.go_crazy_ternary_ver(6))
        self.assertEqual("7", self.nabeatsu.go_crazy_ternary_ver(7))
        self.assertEqual("8", self.nabeatsu.go_crazy_ternary_ver(8))
        self.assertEqual("9!", self.nabeatsu.go_crazy_ternary_ver(9))
        self.assertEqual("10", self.nabeatsu.go_crazy_ternary_ver(10))
        self.assertEqual("11", self.nabeatsu.go_crazy_ternary_ver(11))
        self.assertEqual("12!", self.nabeatsu.go_crazy_ternary_ver(12))
        self.assertEqual("13!", self.nabeatsu.go_crazy_ternary_ver(13))
        self.assertEqual("14", self.nabeatsu.go_crazy_ternary_ver(14))
        self.assertEqual("15!", self.nabeatsu.go_crazy_ternary_ver(15))
        self.assertEqual("16", self.nabeatsu.go_crazy_ternary_ver(16))
        self.assertEqual("17", self.nabeatsu.go_crazy_ternary_ver(17))
        self.assertEqual("18!", self.nabeatsu.go_crazy_ternary_ver(18))
        self.assertEqual("19", self.nabeatsu.go_crazy_ternary_ver(19))
        self.assertEqual("20", self.nabeatsu.go_crazy_ternary_ver(20))
        self.assertEqual("21!", self.nabeatsu.go_crazy_ternary_ver(21))
        self.assertEqual("22", self.nabeatsu.go_crazy_ternary_ver(22))
        self.assertEqual("23!", self.nabeatsu.go_crazy_ternary_ver(23))
        self.assertEqual("24!", self.nabeatsu.go_crazy_ternary_ver(24))
        self.assertEqual("25", self.nabeatsu.go_crazy_ternary_ver(25))
        self.assertEqual("26", self.nabeatsu.go_crazy_ternary_ver(26))
        self.assertEqual("27!", self.nabeatsu.go_crazy_ternary_ver(27))
        self.assertEqual("28", self.nabeatsu.go_crazy_ternary_ver(28))
        self.assertEqual("29", self.nabeatsu.go_crazy_ternary_ver(29))
        self.assertEqual("30!", self.nabeatsu.go_crazy_ternary_ver(30))
        self.assertEqual("31!", self.nabeatsu.go_crazy_ternary_ver(31))
        self.assertEqual("32!", self.nabeatsu.go_crazy_ternary_ver(32))
        self.assertEqual("33!", self.nabeatsu.go_crazy_ternary_ver(33))
        self.assertEqual("34!", self.nabeatsu.go_crazy_ternary_ver(34))
        self.assertEqual("35!", self.nabeatsu.go_crazy_ternary_ver(35))
        self.assertEqual("36!", self.nabeatsu.go_crazy_ternary_ver(36))
        self.assertEqual("37!", self.nabeatsu.go_crazy_ternary_ver(37))
        self.assertEqual("38!", self.nabeatsu.go_crazy_ternary_ver(38))
        self.assertEqual("39!", self.nabeatsu.go_crazy_ternary_ver(39))
        self.assertEqual("40", self.nabeatsu.go_crazy_ternary_ver(40))

if __name__ == "__main__":
    unittest.main()
